/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package JavaCalendarPackage;

import javax.swing.JButton;

/**
 *
 * @author sniffel
 */
class Cells extends JButton {
    public Cells() {
        setContentAreaFilled(false);
        setBorder(null);
    }
}


public class JPanelDates extends javax.swing.JPanel {

    /**
     * Creates new form JPanelDates
     */
    public JPanelDates() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        Cells btnMon = new Cells();

        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(7, 7));

        jButton1.setText("jButton1");
        btnMon.setText("MON");
        add(btnMon);
        add(jButton1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
